"use client";
import { SelectControl } from "@/components/research/select-control";
import Link from "next/link";
import { useEffect,useState } from "react";
import { getFinancials,type BackendFinancialsResponse } from "@/lib/api";
import { userStorage,flushStorage,hasPendingChanges } from "@/lib/user-storage";
import { format } from "@/lib/research";
import { CompanySearch } from "@/components/research/company-search";
import { ChatDock } from "@/components/research/chat-dock";
type Holding={id:string;symbol:string;quantity:number;cost:number;currency:string};
export default function Portfolio() {
  const [holdings,setHoldings]=useState<Holding[]>([]);const [data,setData]=useState<Record<string,BackendFinancialsResponse>>({});const [ready,setReady]=useState(false);const [symbol,setSymbol]=useState("");const [quantity,setQuantity]=useState("");const [cost,setCost]=useState("");const [currency,setCurrency]=useState("USD");const [message,setMessage]=useState("");const [edit,setEdit]=useState<string|null>(null);
  useEffect(()=>{try{const v=JSON.parse(userStorage.getItem("marketly.holdings")||"[]");if(Array.isArray(v))setHoldings(v.filter(h=>h&&typeof h.symbol==="string"&&Number.isFinite(h.quantity)&&Number.isFinite(h.cost)).slice(0,50));}catch{setMessage("Holdings could not be restored.");}setReady(true);},[]);
  const key=[...new Set(holdings.map(h=>h.symbol))].join(",");
  useEffect(()=>{let alive=true;const symbols=key.split(",").filter(Boolean);void(async()=>{for(let i=0;i<symbols.length;i+=3){await Promise.allSettled(symbols.slice(i,i+3).map(async s=>{try{const d=await getFinancials(s);if(alive)setData(v=>({...v,[s]:d}));}catch{/* Missing quotes remain unavailable. */}}));if(!alive)break;}})();return()=>{alive=false;};},[key]);
  async function persist(next:Holding[]){setHoldings(next);userStorage.setItem("marketly.holdings",JSON.stringify(next));await flushStorage();setMessage(hasPendingChanges()?"Holdings saved locally; synchronization needs attention.":"Holdings saved.");}
  function submit(e:React.FormEvent){e.preventDefault();const q=Number(quantity),c=Number(cost);if(!/^[A-Z0-9][A-Z0-9.:-]{0,19}$/.test(symbol)||!Number.isFinite(q)||q<=0||!Number.isFinite(c)||c<0){setMessage("Enter a valid ticker, positive quantity and non-negative cost.");return;}if(!edit&&holdings.length>=50){setMessage("Up to 50 holdings are supported.");return;}const h={id:edit||crypto.randomUUID(),symbol,quantity:q,cost:c,currency};void persist(edit?holdings.map(v=>v.id===edit?h:v):[...holdings,h]);setEdit(null);setQuantity("");setCost("");setSymbol("");}
  const valued=holdings.map(h=>{const d=data[h.symbol];const price=d?.info?.currency===h.currency?(d.quote?.c??d.quote?.currentPrice??null):null;return{...h,price,value:price==null?null:price*h.quantity,sector:d?.info?.sector};});
  const currencies=[...new Set(holdings.map(h=>h.currency))];
  return <main className="account-page portfolio-page"><nav><Link href="/">← Research</Link><Link href="/settings">Profile & preferences</Link><Link href="/compare">Compare companies</Link></nav><div className="eyebrow">YOUR WORKSPACE</div><h1>Portfolio</h1><p>Record holdings and analyze concentration with verified company data.</p><div className="portfolio-totals">{currencies.map(c=>{const rows=valued.filter(h=>h.currency===c);const known=rows.filter(h=>h.value!=null);return <div key={c}><small>{c} · priced holdings</small><strong>{format(known.reduce((n,h)=>n+h.value!,0),"money",c)}</strong><span>{known.length}/{rows.length} holdings valued</span></div>;})}</div>
    <form className="account-form" onSubmit={submit}><h2>{edit?"Edit holding":"Add holding"}</h2><CompanySearch compact onSelect={c=>setSymbol(c.symbol)}/><div className="account-grid"><label>Ticker<input required value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())}/></label><label>Quantity<input type="number" min="0.000001" step="any" required value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><label>Average cost per share<input type="number" min="0" step="any" required value={cost} onChange={e=>setCost(e.target.value)}/></label><label>Cost currency<SelectControl ariaLabel="Holding currency" value={currency} onChange={e=>setCurrency(e.target.value)}>{["USD","EUR","GBP","CHF","CAD","JPY"].map(c=><option key={c}>{c}</option>)}</SelectControl></label></div><button disabled={!ready} className="primary-button">{edit?"Save holding":"Add holding"}</button>{edit&&<button type="button" onClick={()=>{setEdit(null);setSymbol("");setQuantity("");setCost("");}}>Cancel edit</button>}</form><p role="status">{message}</p>
    <div className="comparison-table-wrap"><table className="comparison-table"><thead><tr><th>Company</th><th>Quantity</th><th>Average cost</th><th>Price</th><th>Market value</th><th>Unrealized P/L</th><th>Actions</th></tr></thead><tbody>{valued.map(h=><tr key={h.id}><th>{h.symbol}<small>{h.sector||"Sector unavailable"}</small></th><td>{format(h.quantity)}</td><td>{format(h.cost,"money",h.currency)}</td><td>{format(h.price,"money",h.currency)}</td><td>{format(h.value,"money",h.currency)}</td><td>{format(h.value==null?null:h.value-h.cost*h.quantity,"money",h.currency)}</td><td><button onClick={()=>{setEdit(h.id);setSymbol(h.symbol);setQuantity(String(h.quantity));setCost(String(h.cost));setCurrency(h.currency);}}>Edit</button> · <button onClick={()=>void persist(holdings.filter(v=>v.id!==h.id))}>Remove</button></td></tr>)}</tbody></table></div>
    {!holdings.length&&<p>No holdings yet.</p>}<p className="disclosure">Currencies are kept separate. Unavailable or currency-mismatched prices are excluded from totals. Cost-based P/L excludes fees, dividends and realized transactions.</p><button className="secondary-button" onClick={()=>window.dispatchEvent(new CustomEvent("marketly-research-question",{detail:"Analyze my portfolio concentration, sector exposure, liquidity and key risks. Use only the holdings I opted to share and state any gaps. If holdings access is disabled, ask me to enable it in preferences."}))}>Analyze portfolio in chat ↗</button><ChatDock scope="MARKET" context={{scope:"Portfolio",note:"Use holdings only when supplied through the user's explicit preference."}} />
  </main>;
}
