"use client";
import { useEffect,useState } from "react";
import { BarChart,Bar,CartesianGrid,Legend,ResponsiveContainer,Tooltip,XAxis,YAxis } from "recharts";
import { format } from "@/lib/research";
type Earnings = {period:string;actual:number|null;estimate:number|null;surprise:number|null;surprisePercent:number|null;currency:string|null};
export function Expectations({symbol}:{symbol:string}) {
  const [data,setData]=useState<{earnings:Earnings[];note:string;source:string;fetchedAt:string}>(); const [error,setError]=useState(""); const [retry,setRetry]=useState(0);
  useEffect(()=>{const c=new AbortController();setData(undefined);setError("");void fetch(`/api/backend/companies/${encodeURIComponent(symbol)}/expectations`,{signal:c.signal}).then(async r=>{if(!r.ok)throw Error("Earnings expectations are unavailable from the configured provider.");setData(await r.json());}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[symbol,retry]);
  return <section className="research-section"><h2>Expectations vs actuals</h2><p className="disclosure">Consensus EPS and reported EPS paired by fiscal period.</p>{error?<p role="alert">{error} <button className="text-button" onClick={()=>setRetry(retry+1)}>Retry</button></p>:!data?<p>Loading expectations…</p>:<>{data.earnings.some((e)=>e.actual!=null||e.estimate!=null)&&<div className="expectations-chart" role="img" aria-label="Actual versus consensus EPS by fiscal period; exact values below"><ResponsiveContainer width="100%" height="100%"><BarChart data={[...data.earnings].reverse()} margin={{top:12,right:18,bottom:12,left:4}}><CartesianGrid vertical={false} stroke="#2b3033"/><XAxis dataKey="period" tick={{fontSize:12}}/><YAxis width={48} tick={{fontSize:12}}/><Tooltip cursor={{fill:"#ffffff08"}} formatter={(value:number)=>value.toFixed(2)} contentStyle={{background:"#16191b",border:"1px solid #3b4348",color:"#ddd"}}/><Legend/><Bar dataKey="estimate" name="Consensus EPS" fill="#8eabd0" radius={[2,2,0,0]} isAnimationActive={false}/><Bar dataKey="actual" name="Actual EPS" fill="#7fc9bb" radius={[2,2,0,0]} isAnimationActive={false}/></BarChart></ResponsiveContainer></div>}{!data.earnings.length&&<p className="disclosure">No verified earnings pairs were returned.</p>}<details className="expectations-evidence"><summary>Exact figures & source notes</summary><div className="comparison-table-wrap"><table className="comparison-table"><thead><tr><th>Period</th><th>EPS estimate</th><th>EPS actual</th><th>Provider surprise</th><th>Surprise %</th></tr></thead><tbody>{data.earnings.map((e)=><tr key={e.period}><th>{e.period}</th><td>{format(e.estimate)}</td><td>{format(e.actual)}</td><td>{format(e.surprise)}</td><td>{format(e.surprisePercent,"percent")}</td></tr>)}</tbody></table></div>{!data.earnings.length&&<p>No verified earnings pairs were returned.</p>}<p className="disclosure">{data.note}</p><p className="disclosure">{data.source} · Retrieved {new Date(data.fetchedAt).toLocaleString()}. Currency and estimate timestamp are unavailable when not supplied.</p></details></>}</section>;
}
