"use client";
import { useEffect,useState } from "react";
import { CartesianGrid,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis } from "recharts";
import { format } from "@/lib/research";
type Earnings = {period:string;actual:number|null;estimate:number|null;surprise:number|null;surprisePercent:number|null;currency:string|null};
function ActualDot({cx=0,cy=0,payload}:{cx?:number;cy?:number;payload?:Earnings}) { const missed=payload?.actual!=null&&payload?.estimate!=null&&payload.actual<payload.estimate; return <circle cx={cx} cy={cy} r={6} fill={missed?"#e06c75":"#70bd8b"} stroke="#0b0e0f" strokeWidth={2}/>; }
export function Expectations({symbol}:{symbol:string}) {
  const [data,setData]=useState<{earnings:Earnings[];note:string;source:string;fetchedAt:string}>(); const [error,setError]=useState(""); const [retry,setRetry]=useState(0);
  useEffect(()=>{const c=new AbortController();setData(undefined);setError("");void fetch(`/api/backend/companies/${encodeURIComponent(symbol)}/expectations`,{signal:c.signal}).then(async r=>{if(!r.ok)throw Error("Earnings expectations are unavailable from the configured provider.");setData(await r.json());}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[symbol,retry]);
  return <section className="research-section"><h2>Expectations vs actuals</h2><p className="disclosure">Consensus EPS and reported EPS paired by fiscal period. Green beats or meets consensus; red misses.</p>{error?<p role="alert">{error} <button className="text-button" onClick={()=>setRetry(retry+1)}>Retry</button></p>:!data?<p>Loading expectations…</p>:<>{data.earnings.some((e)=>e.actual!=null||e.estimate!=null)&&<div className="expectations-chart" role="img" aria-label="Actual versus consensus EPS points by fiscal period; exact values below"><ResponsiveContainer width="100%" height="100%"><LineChart data={[...data.earnings].reverse()} margin={{top:18,right:24,bottom:18,left:4}}><CartesianGrid vertical={false} stroke="#2b3033"/><XAxis dataKey="period" tick={{fontSize:12}}/><YAxis width={52} tick={{fontSize:12}}/><Tooltip cursor={{stroke:"#3b4348",strokeDasharray:"3 4"}} formatter={(value:number)=>value.toFixed(2)} contentStyle={{background:"#16191b",border:"1px solid #3b4348",color:"#ddd"}}/><Line type="linear" dataKey="estimate" name="Consensus EPS" stroke="transparent" dot={{r:6,fill:"#0b0e0f",stroke:"#92999d",strokeWidth:2}} activeDot={{r:7,fill:"#0b0e0f",stroke:"#c1c7ca",strokeWidth:2}} isAnimationActive={false}/><Line type="linear" dataKey="actual" name="Actual EPS" stroke="transparent" dot={<ActualDot/>} activeDot={<ActualDot/>} isAnimationActive={false}/></LineChart></ResponsiveContainer><div className="expectations-legend"><span><i className="estimate-dot"/>Consensus</span><span><i className="beat-dot"/>Beat / met</span><span><i className="miss-dot"/>Missed</span></div></div>}{!data.earnings.length&&<p className="disclosure">No verified earnings pairs were returned.</p>}<details className="expectations-evidence"><summary>Exact figures & source notes</summary><div className="comparison-table-wrap"><table className="comparison-table"><thead><tr><th>Period</th><th>EPS estimate</th><th>EPS actual</th><th>Provider surprise</th><th>Surprise %</th></tr></thead><tbody>{data.earnings.map((e)=><tr key={e.period}><th>{e.period}</th><td>{format(e.estimate)}</td><td>{format(e.actual)}</td><td>{format(e.surprise)}</td><td className={(e.surprise??0)<0?"negative":"positive"}>{format(e.surprisePercent,"percent")}</td></tr>)}</tbody></table></div><p className="disclosure">{data.note}</p><p className="disclosure">{data.source} · Retrieved {new Date(data.fetchedAt).toLocaleString()}. Currency and estimate timestamp are unavailable when not supplied.</p></details></>}</section>;
}
