"use client";
import { useState } from "react";
import { Bookmark, ArrowUpRight, Trash2, Search } from "lucide-react";
import { type SavedResearch, metrics, format } from "@/lib/research";
import { CompanyLogo } from "./company-logo";
import { SavedConversations } from "./saved-conversations";
export function ResearchLibrary({items,onOpen,onDelete,onExplore}:{items:SavedResearch[];onOpen:(item:SavedResearch)=>void;onDelete:(id:string)=>void;onExplore:()=>void}) {
 const [query,setQuery]=useState("");const [selected,setSelected]=useState("");const [tab,setTab]=useState("Snapshots");
 const filtered=items.filter(i=>`${i.name} ${i.symbol}`.toLowerCase().includes(query.toLowerCase()));const current=filtered.find(i=>i.id===selected)||filtered[0];const values=current?metrics(current.financials):null;
 return <section className="library-view"><div className="section-heading"><div><div className="eyebrow">YOUR RESEARCH</div><h1>Saved research</h1><p>Company snapshots and AI conversations, ready to revisit.</p></div><button className="primary-button" onClick={onExplore}>New research <ArrowUpRight size={14}/></button></div><div className="ui-toolbar">{["Snapshots","Conversations"].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t}</button>)}{tab==="Snapshots"&&<label className="library-search"><Search size={15}/><input aria-label="Search saved research" placeholder="Search company or ticker…" value={query} onChange={e=>setQuery(e.target.value)}/></label>}</div>
 {tab==="Conversations"?<SavedConversations/>:<div className="research-library-layout"><div className="research-library-list" aria-label="Saved company snapshots">{filtered.map(item=><button key={item.id} className={current?.id===item.id?"selected":""} aria-pressed={current?.id===item.id} onClick={()=>setSelected(item.id)}><CompanyLogo symbol={item.symbol}/><span><strong>{item.name}</strong><small>{item.symbol} · {new Date(item.savedAt).toLocaleDateString()}</small></span><Bookmark size={14}/></button>)}{!filtered.length&&<div className="empty-state">{query?"No matching research.":"Save a company snapshot to start your library."}</div>}</div><article className="research-reading-pane">{current&&values?<><div className="eyebrow">{current.symbol} / COMPANY SNAPSHOT</div><h2>{current.name}</h2><p className="disclosure">Saved {new Date(current.savedAt).toLocaleString()}. Values reflect this snapshot, not current quotes.</p><div className="library-metrics">{[["Revenue",format(values.revenue,"money")],["Net margin",format(values.margin,"percent")],["P/E",format(values.pe)],["Market cap",format(values.marketCap,"money")]].map(([label,value])=><div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div><h3>Headlines saved with this research</h3>{current.news.slice(0,5).map((n,i)=><p key={n.url||i} className="library-headline">{n.headline}<small>{n.source}</small></p>)}{!current.news.length&&<p className="disclosure">No headlines in this snapshot.</p>}<div className="ui-toolbar"><button onClick={()=>onOpen(current)}>Open full research <ArrowUpRight size={14}/></button><button aria-label={`Delete saved ${current.symbol} research`} onClick={()=>onDelete(current.id)}><Trash2 size={14}/> Delete snapshot</button></div></>:<div className="empty-state"><Bookmark size={28}/><p>Select saved research to read it here.</p></div>}</article></div>}
 </section>;
}
